name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: project-76b5e515-21a1-4a89-82f
  REGION: us-central1
  SERVICE_NAME: stock-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
        service_account: '${{ secrets.GCP_SA_EMAIL }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker Client
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build and Push Container
      run: |
        gcloud artifacts repositories create cloud-run-source-deploy \
          --repository-format=docker --location=${{ env.REGION }} --quiet || true
        
        IMAGE_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/${{ env.SERVICE_NAME }}:${{ github.sha }}"
        docker build -f backend/Dockerfile -t $IMAGE_TAG backend
        docker push $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: ${{ env.IMAGE_TAG }}
        flags: |
          --allow-unauthenticated
          --set-cloudsql-instances="project-76b5e515-21a1-4a89-82f:us-central1:emil-ia-postgres-mvp"
          --set-env-vars="CLOUD_SQL_CONNECTION_NAME=project-76b5e515-21a1-4a89-82f:us-central1:emil-ia-postgres-mvp,DB_USER=postgres,DB_PASSWORD=root,DB_NAME=postgres"